import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://p.trellocdn.com/power-up.min.css"
        />
      </head>
      <body className={inter.className}>
        {children}
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" />
        <Script
          src={`https://p.trellocdn.com/power-up.min.js?key=${process.env.TRELLO_POWERUP_KEY}`}
        />
      </body>
    </html>
  );
}
